server:
  port: 10086 # 服务端口
spring:
  application:
    name: eurekaserver # eureka的服务名称
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:  # eureka的地址信息
    #  defaultZone: http://127.0.0.1:10087/eureka,http://localhost:10088/eureka
      defaultZone: http://127.0.0.1:10086/eureka
#  instance:
#    hostname: eurekaserver10086